# Site wide configuration

title:            JOSÉ LUIS LÓPEZ PINO
locale:           en_UK
url:              http://lopezpino.es

# Jekyll configuration

permalink:   /:year/:month/:day/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Pino
  avatar: jose_luis_lopez_pino.jpg
  bio: "I (infrequently) blog about data science, business intelligence, big data, web technologies and free software."
  email:
  disqus-shortname: lopezpinoes
  twitter: jllopezpino
  facebook: #username
  google:
    plus: #username
    analytics: UA-8638399-5
    verify: wAiUsi4VuDIUEBo3CKFN8je7G5NDyJIFYLxf_1sZthk
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: joseluislopezpino
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
